### ISSUE TITLE
Drag and Drop a+ Apple

### ISSUE THREAD

**Issue by gemguardian** [h5p/h5p-drag-n-drop#4]
Hello, 
We have noticed that the https://h5p.org/drag-and-drop is not interacting well with APPLE devices, especially when used in CoursePresentation - when you try to drag the image it just swipes a slide left or right (depending on your own movement). 

We could not reproduce this issue on Samsung/Android, so we think it is caused by an issue on Apple. But what we did notice is that the Drag-words has a 'work-around' where clicking on the word, and then on the field you want to drop it actually does work on Apple. 

We think it would be great if this solutions would also be for the Drag and Drop itself. 

Gemma

**Comment by otacke** [comment]
Hi Gemma!

Wrong repository (this one is actually just helping library for drag-and-drop components in the editor). BUT: That bug was fixed recently (https://github.com/h5p/h5p-drag-question/commit/d067db8ab66e5c1c9a9318055f603c39f3d484b7 and https://h5p.org/node/1298227) and I assume all that's left is for the H5P core team to release an update.

Cheers,
Oliver

**Comment by gemguardian** [comment]
Oh sorry thought i had the right one:) But thank you for pointing out into the right direction.
